### ISSUE TITLE
Make buttons on the workout screen the same width

### ISSUE THREAD

**Issue by JJB9922** [JJB9922/MuayThaideas#6]
As a UI, I want consistent button sizing on the workout screen

![Screenshot_20231118-011451.png](https://github.com/JJB9922/MuayThaideas/assets/105116192/ae7d7efd-672c-4e60-8e4f-7761f1e1fa28)

**Comment by mnajibi** [comment]
Hi, can I work on this issue? and if yes could you please assign me to it? 
Thanks

**Comment by JJB9922** [comment]
Sure, thanks Maryam 😊
